export const FETCH_PRODUCTS = "FETCH_PRODUCTS"

export const PRODUCTS_FETCHED = "PRODUCTS_FETCHED"

export const ERROR_FETCHING_PRODUCTS = "ERROR_FETCHING_PRODUCTS"

export const ADD_PRODUCT = "ADD_PRODUCT"